# Generated by Django 5.1.3 on 2024-12-03 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="description",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="updated_at",
        ),
    ]
